# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - release-*
  paths:
    include:
    - 03.activityLog/*

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SKT_MG_stg'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    workingDirectory: '03.activityLog'
    scriptPath: '03.activityLog/updateActivityLog.ps1'
    arguments: '-env stg'