# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 02.RBAC/*

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SKT_MG_prd'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    workingDirectory: '02.RBAC'
    scriptPath: '02.RBAC/updateCustomRoles.ps1'
    arguments: '-env prd'